---
name: Secret Scan

on:
  push: {}
  pull_request: {}

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install gitleaks
        env:
          GITLEAKS_VERSION: "8.18.1"
        run: |
          URL="https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz"
          curl -sSL "${URL}" -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run gitleaks
        run: gitleaks detect --redact --verbose
